#!/bin/sh

# aligns tsv columns by inserting spaces so that each column has the same width
# constraint: fields must not contain consecutive spaces

column -s $'\t' -t "$1" | sed 's/[[:space:]]*$//' |
    sed 's/\( *\)  /\1\t/g' > "$1.tmp"
mv "$1.tmp" "$1"
